name: Publish to package managers

on:
  release:
    types: 
      - published

  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: 15722UsefulApp.PortForCommandPalette
          installers-regex: '\.Msix$'
          token: ${{ secrets.WINGETCREATE_GITHUB }}
